CHANGELOG.md
pom.xml
src/descriptor/service.sdl

updates for CDAP 3.1.0

---

CHANGELOG.md
src/descriptor/service.sdl

Merge latest changes back to develop.

Merge Release 3.2 branch back to develop

---

src/descriptor/service.sdl

Made the descriptions identical to the CDAP default.xml.

Updates to descriptions. De-tabbed file.

---

src/descriptor/service.sdl

Removed extra spaces after periods and before colons.

Fixed usages of "CDAP Kafka" for metadata.

---

src/descriptor/service.sdl
src/scripts/cdap-control.sh

Merge release/3.4 changes into RC branch

Merge release/3.4 changes into RC branch

---

src/descriptor/service.sdl

https://issues.cask.co/browse/CDAP-5760

enable audit log and allow it to be configurable in wizard

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

preparing for 3.3.2 release, updating version and changelog

update version and changelog for 3.3.2 release

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

version bump for 3.4.1 release

---

src/descriptor/service.sdl

update CDAP label and description per marketing.  These show up in the "Add Service" wizard.

update CDAP label and description

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

3.4.2 release version bump and changelog update

Version bump for 3.4.2 release

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

- updates versions, repo url, and changelog for 3.5.0 release

version bump for 3.5.0 release

---

src/descriptor/service.sdl

fix commas.
validator passes
```
$ java -jar ~/git/cm_ext/validator/target/validator.jar -s service.sdl -l SPARK_ON_YARN
Validating: service.sdl
Validation succeeded.
```

fix commas

---

src/scripts/cdap-control.sh

This allows a 4.0 CSD to be used with older CDAP parcels.

Remain compatible with pre-4.0 parcels

---

pom.xml
src/descriptor/service.sdl

bump develop to ``4.0.0-SNAPSHOT``

version bump develop

---

src/aux/logback-container.xml.default

Update logback-container.xml file, based upon the change in https://github.com/caskdata/cdap/pull/6966.

Update logback-container.xml file, based upon a change in CDAP

---

src/descriptor/service.sdl

update the default value for operational_stats_extensions_dir property

update default value

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

version bump and changelog update for 4.0 release.

Version bump and Changelog update for 4.0 release

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

Version bump and changelog update for 4.0.1 release

Version bump for 4.0.1 release

---

pom.xml
src/descriptor/service.sdl

bump version for develop branch

bump version for develop

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

version bump for 4.1.0 release

---

pom.xml
src/descriptor/service.sdl

bump version to 4-1-1-snapshot

---

pom.xml
src/descriptor/service.sdl

bump develop version to 4.2.0-SNAPSHOT

bump develop version

---

src/descriptor/service.sdl

Corrects the delimiter according to CDAP-8896.  fixes CDAP-8897

set delimiter to comma per CDAP-8897

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

Version bump for 4.1.2 release

---

src/descriptor/service.sdl

add spark compat dir

---

src/descriptor/service.sdl

https://issues.cask.co/browse/CDAP-11515
Update CSD with JobQueue debug tool

CDAP-11515 add JobQueue debug tool

---

src/descriptor/service.sdl

https://issues.cask.co/browse/CDAP-11531
New Properties
hbase.version.resolution.strategy
hive.version.resolution.strategy
Modified description
security.authorization.cache.ttl.secs

add new properties

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

version bump for 4.2.0 release

---

src/descriptor/service.sdl

escape quotes

---

pom.xml
src/descriptor/service.sdl

update parcel repo

---

pom.xml
src/descriptor/service.sdl

bumping CSD version to 4.3.0-SNAPSHOT.
Doing this in develop (belatedly), then will cut release branch.

version bump for 4.3

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

- Adds compatibility check for CDAP Parcel ( Issues: #172 #173 [CDAP-4874](https://issues.cask.co/browse/CDAP-4874) )
- Adds configurations for CDAP 4.3 release ( Issues: #175 [CDAP-12235](https://issues.cask.co/browse/CDAP-12235) )
- Removes configurations which are designated final ( Issues: #176 [CDAP-11944](https://issues.cask.co/browse/CDAP-11944) )

Feature/version bump 4.3

---

pom.xml
src/descriptor/service.sdl

version bump for release 4.3 branch

version bump release 4.3 branch

---

src/descriptor/service.sdl

Update default configurations per https://issues.cask.co/browse/CDAP-12767
Related PRs:
CDAP (packages): https://github.com/caskdata/cdap/pull/9737
CSD: https://github.com/caskdata/cm_csd/pull/187
Ambari: https://github.com/caskdata/cdap-ambari-service/pull/288

CDAP-12767 update default configurations

---

pom.xml
src/descriptor/service.sdl

Version bump 4.3 to next snapshot

version bump 4.3

---

src/descriptor/service.sdl

partially fixes https://issues.cask.co/browse/CDAP-13416

update PrintGCDateStamps to match cdap-default.xml

---

src/descriptor/service.sdl

Remove max value. CM throws a warning in the server logs.

update app program port

---

src/descriptor/service.sdl

Update runtime dir default value

CDAP-13903

---

src/descriptor/service.sdl

change the `[hbase,hive].version.resolution.strategy` configurations to radio buttons, for usability.

update resolution strategy configurations to radio buttons for usability

---

CHANGELOG.md
pom.xml
src/descriptor/service.sdl

version bump for 5.1.0 release

---

src/scripts/cdap-control.sh

handles the CDAP UI entrypoint change made in https://github.com/cdapio/cdap/pull/10883/commits/83356757820b0bf0874dcd836907c16f050a7155 in a backwards compatible fashion 
- moves the version parsing logic to earlier in the file
- uses the determined version to set the UI entrypoint

modify cdap-ui entrypoint name based on detected version

---

src/descriptor/service.sdl

updating the default market url to the new location

update default market url
