src/descriptor/service.sdl
=> make app.template.dir configurable in wizard

src/scripts/cdap-control.sh
This supports CDAP-1174 as modified by caskdata/cdap#4712 by defining functions calling the older function names if the functions don't exist. This gives us backwards compatibility with older Parcels.
=> CDAP-1174 Namespace start script functions

src/scripts/cdap-control.sh
=> pass any args to remapped functions

src/descriptor/service.sdl
quick bugfix.
It was creating ``hdfs:///user/cdap`` by interpolating ``/user/${root.namespace}`` instead of ``/user/${hdfs.user}``
=> create user dir for the hdfs.user property, not root.namespace

src/descriptor/service.sdl
Enable explore by default in Cloudera Manager configuration.
Related PR in CDAP repo:
https://github.com/caskdata/cdap/pull/4859
=> Enable explore by default

CHANGELOG.md, src/descriptor/service.sdl
=> CDAP-4699 add configuration for dashboard.router.check.timeout.secs

src/descriptor/service.sdl
increase the default ``dashboard.router.check.timeout.secs`` value from 1-min to 3-min.  I have seen a case where 1-min is too short on an automated cluster spinup/restart using the CM api.
=> increase router UI timeout to 3min

src/descriptor/service.sdl
fixes https://issues.cask.co/browse/CDAP-5035.  fixing in release/3.3 and will merge to develop for 3.4.
=> add data.tx.timeout parameter

src/scripts/cdap-control.sh
fixes [CDAP-5058](https://issues.cask.co/browse/CDAP-5058).
=> remove redundant cdap kinit

src/scripts/cdap-control.sh
Otherwise, it is treated as a single string argument, not multiple arguments...
=> Do not quote OPTS

src/descriptor/service.sdl
fixes https://issues.cask.co/browse/CDAP-5620
The logback default directory ``/var/log/cdap`` is not exposed in CM as a configuration because the field name is incorrect.  this fixes that.
And note this is not caught by their sdl validator tool.
https://github.com/cloudera/cm_ext/wiki/Service-Descriptor-Language-Reference#logging
=> fix logging modifiable attribute name

src/scripts/cdap-control.sh
Setting this before running `cdap_set_hive_classpath` means SPARK_HOME is set for that function. This allows for Hive on Spark to function even when Spark is not set as a direct dependency of CDAP in Cloudera Manager.
This is the CSD side for caskdata/cdap#5740
=> CDAP-5875 Check SPARK_HOME before cdap_set_hive_classpath

src/scripts/cdap-control.sh
fixes https://issues.cask.co/browse/CDAP-5891
Set java max heap for the upgrade tool commands. This will set it to whatever the Master Max Heapsize CM configuration is.
reopen of https://github.com/caskdata/cm_csd/pull/83 against the right branch
=> set JAVA_HEAPMAX for upgrade tool

src/descriptor/service.sdl, src/scripts/cdap-control.sh
fixes https://issues.cask.co/browse/CDAP-5956
CSD will now set the $CDAP_JAVA_OPTS env var, which the control script will include in the java invocation instead of $OPTS. This is because $OPTS is unmodifiable in CDAP's init framework. see CDAP-5956 for more details.
reopen of https://github.com/caskdata/cm_csd/pull/85 against the right branch
=> use CDAP_JAVA_OPTS instead of OPTS

src/descriptor/service.sdl
fixes [CDAP-6182](https://issues.cask.co/browse/CDAP-6182)
=> expose yarn scheduler queue configs

src/descriptor/service.sdl
Adds ``router.server.[address,port]`` properties as system-wide, and configurable in wizard.  Updates `` router.[ssl].bind.[address,port]`` to be router-specific.  ``router.bind.address`` defaults to ``0.0.0.0`` and ``router.server.address`` defaults to ``127.0.0.1``, so default configs should still work.
Fixes [CDAP-2501](https://issues.cask.co/browse/CDAP-2501)
Fixes [CDAP-6974](https://issues.cask.co/browse/CDAP-6974)
=> make router server/bind props service-wide and configurable in wizard

src/scripts/cdap-control.sh
the control.sh script was still looking for the old property name, causing kafka.seed.brokers to be empty
=> update port setting name in kafka quorum detection

CHANGELOG.md, pom.xml, src/descriptor/service.sdl, src/scripts/cdap-control.sh
=> 3.5.1 release, feature/fix upgrade classpath

src/scripts/cdap-control.sh
This sources the new location for CDAP functions, after caskdata/cdap#6574 is merged.
=> Source new functions.sh script from CDAP-1280

src/scripts/cdap-control.sh
This adds back missing variables that used to get sourced from the parcel component-env.sh scripts.  We should follow this up with some refactoring of cdap's ``functions.sh`` to help simplify this.  this is just to get it working.
=> set vars formerly in component-env scripts

src/descriptor/service.sdl
update default UI port to ``11011`` with the rest of CDAP for 4.0
=> set default UI bind port to 11011

src/scripts/cdap-control.sh
=> support explore.conf.dirs for cdap 4.0

src/descriptor/service.sdl, src/scripts/cdap-control.sh
fixes https://issues.cask.co/browse/CDAP-7555.  Adds ``jvmBased`` declaration to CSD java roles, and passes the resultant ``$CSD_JAVA_OPTS`` to the launched process.
=> add jvmBased declaration to jvm roles, and handle CSD_JAVA_OPTS 

src/scripts/cdap-control.sh
- significant change to classpath ordering, to include the up-to-date configurations of CDAP service dependencies (HDFS, YARN, HBASE, HIVE, SPARK).  See https://issues.cask.co/browse/CDAP-7556.
Implementation is just to set these config directories in the ``CLASSPATH`` before calling ``cdap_set_classpath``, which will append.
=> add service dependency configs to beginning of CLASSPATH

src/scripts/cdap-control.sh
If the CSD control script fails when sourcing the CDAP functions.sh/common.sh, it leaves no error and is hard to debug.  Adding a few logging statements to help with any such future issues.
=> add more logging to help debug sourcing failures

src/descriptor/service.sdl
generates ``cdap-security.xml`` with the appropriate parameters per role, and also excludes them from each role's ``cdap-site.xml``.  Makes it possible to manually configure SSL, fixing the first part of https://issues.cask.co/browse/CDAP-8168
=> generate cdap-security.xml

src/descriptor/service.sdl, src/scripts/cdap-control.sh
fixes [CDAP-8227](https://issues.cask.co/browse/CDAP-8227)
=> add cdap coprocessor setup utility

src/descriptor/service.sdl
Fixes [CDAP-5453](https://issues.cask.co/browse/CDAP-5453), adds simple rolling restart functionality.
=> [CDAP-5453] add simple rolling restart capability

src/descriptor/service.sdl, src/scripts/cdap-control.sh
reverts most of #135, leaving only the coprocessor check on startup.
Having it as a command is redundant, and we have no way for the user to optionally specify ``force``.  Running it with ``force`` will require it be run from the cmdline, made easier now by https://github.com/caskdata/cdap/pull/8129
=> remove hbase coprocessor setup command

src/scripts/cdap-control.sh
checks the cdap version before attempting to run the coprocessor setup tool introduced in 4.1.  This allows the 4.1+ csd to still run with older parcels.
=> only run coprocessor setup on cdap 4.1+

src/descriptor/service.sdl
recategorizes the new logging framework related settings and log.publish.partition.key under the Master Role.  This means they will only be rendered in cdap-master's cdap-site.xml.
The primary reason for this are that CM will now automatically create ``log.process.pipeline.config.dir`` and ``log.process.pipeline.lib.dir`` for the user.  (And then keeping related settings together).
we may want to recategorize as many of these new settings as appropriate, while we can
=> move logging framework settings under master role

src/descriptor/service.sdl
works around https://issues.cask.co/browse/CDAP-8750, by giving only 1 option for retry.policy for system services
=> CDAP-8750 constrain system retry policy options

src/descriptor/service.sdl
CM doesn't allow 0 for port configurations by default.  There is a "zeroAllowed" directive, but then if 0 is specified multiple times (like our defaults), CM will complain about port conflicts on hosts.
Therefore, just changing these to ``long`` with a maximum
=> using long instead of port for configs that allow port 0

src/descriptor/service.sdl
fixes [CDAP-8891](https://issues.cask.co/browse/CDAP-8891).
=> add optional authentication parameters

src/scripts/cdap-control.sh
The assumption is that the environment will contain
SPARK_MAJOR_VERSION=2 when CDAP should be using spark2. This is
the same as how HDP does it.
Modified the script to set SPARK_COMPAT, and to set java system
property app.program.spark.compat, which CDAP uses to decide
which spark runtime to use, and which pipeline artifacts to
load.
=> CDAP-11586 update start script to handle spark2

src/descriptor/service.sdl
This is because we do not want users to be able to modify this parameter.
In cdap-default.xml, we will mark it final: https://github.com/caskdata/cdap/pull/8910
=> Remove 'messaging.system.topics' from service.sdl.

src/descriptor/service.sdl
Spark 2 can be installed on CM via a separate parcel.  This adds optional dependencies to CDAP on the spark2 parcel and service.
The necessary control script updates already commited in https://github.com/caskdata/cm_csd/pull/156
=> add optional tag & service dependencies on spark 2

src/descriptor/service.sdl
https://issues.cask.co/browse/CDAP-11531
New properties
- app.program.spark.compat
- data.event.topic
- data.tx.grace.period
- messaging.cache.size.mb
- security.authorization.cache.max.entries
- security.authorization.propagate.privileges
- stream.size.event.topic
- time.event.topic
Removed properties
- security.authorization.cache.enabled
- security.authorization.cache.refresh.interval.secs
Modified Values
- app.artifact.dir
- explore.active.operation.timeout.secs
=> add new properties

CHANGELOG.md, pom.xml, src/descriptor/service.sdl
Version bump for 4.2.2 release.  Includes:
- Add cdap-env.sh to gateway role ( Issues: #168 )
=> version bump for 4.2.2 release

assembly.xml, src/scripts/build-env.sh, src/scripts/cdap-control.sh
first step for [CDAP-4874](https://issues.cask.co/browse/CDAP-4874):
=> write build version into the CSD

src/descriptor/service.sdl, src/scripts/cdap-control.sh
Adds a mechanism to ensure the CSD version is >= the CDAP Parcel version.  This will enforce, particularly for upgrades, that the CSD version is up-to-date.  It is enabled by default, but can be disabled in the cdap configuration.
Resolves [CDAP-4874](https://issues.cask.co/browse/CDAP-4874)
=> check csd/parcel compatibility

src/descriptor/service.sdl
https://issues.cask.co/browse/CDAP-12235
Update properties
Added in 4.3
- app.program.metrics.enabled
- messaging.twill.java.heap.memory.ratio
- messaging.twill.java.reserved.memory.mb
- metrics.hbase.max.scan.threads
- metrics.v2.table.scan.enabled
- program.message.retry.policy.base.delay.ms
- program.message.retry.policy.max.delay.ms
- program.message.retry.policy.max.retries
- program.message.retry.policy.max.time.secs
- program.message.retry.policy.type
- program.status.event.topic
- security.authorization.extension.extra.classpath (Added but it's not in the cdap-default.xml)
- messaging.table.hbase.split.policy (left out of the CSD because it's not recommended to change form the default value)
New default value
- twill.java.heap.memory.ratio(0.6)
Removed in 4.3
- …
=> CDAP-12235 Configuration changes for CSD

src/descriptor/service.sdl
fixes [CDAP-11944](https://issues.cask.co/browse/CDAP-11944).  Removes properties which are designated ``final`` in ``cdap-default.xml`` and which cannot be configured by the user.  Otherwise, the CSD will always render them into cdap-site.xml, generating some log warnings.
=> remove properties which are designated final and cant be configured

src/descriptor/service.sdl
=> add optional dependency on sentry

src/descriptor/service.sdl
fixes https://issues.cask.co/browse/CDAP-12721
This defines a role-level [stopRunner](https://github.com/cloudera/cm_ext/wiki/Service-Descriptor-Language-Reference#stoprunner-1) for the Master role.  This adds a new "Graceful Shutdown Timeout" configuration to the master role, with a default value of 5min.
=> define stopRunner for master role to trigger graceful shutdown

CHANGELOG.md, pom.xml, src/descriptor/service.sdl
4.3.1 release.  Includes:
- Add optional dependency on Sentry ( Issues: #178 )
- Add configurable graceful shutdown timeout ( Issues: #181 #183 [CDAP-12721](https://issues.cask.co/browse/CDAP-12721)
=> version bump for 4.3.1 release

src/descriptor/service.sdl
update JVM options consistently with https://github.com/caskdata/cdap/pull/10124
=> update jvm opts for jdk 8

src/descriptor/service.sdl, src/scripts/cdap-control.sh
This is the config update for 5.0.
https://issues.cask.co/browse/CDAP-13708
The default value for `router_audit_log_enabled` was set to `${security.enabled}` but the build failed with 
`Can not construct instance of java.lang.Boolean from String value 'boolean': only "true" or "false" recognized`
I defaulted to true, but we should consider changing this to a string.
=> CDAP-13708

CHANGELOG.md, pom.xml, src/descriptor/service.sdl
- Update default configurations for better usability ( Issues: #187 [CDAP-12767](https://issues.cask.co/browse/CDAP-12767) )
- Update default JVM options for JDK 8 ( Issues: #191 )
- Update default twill JVM options for JDK 8 ( Issues: #192 [CDAP-13416](https://issues.cask.co/browse/CDAP-13416) )
- Add configurations for CDAP 5.0 release ( Issues: #193 #194 #195 [CDAP-13708](https://issues.cask.co/browse/CDAP-13708) )
=> version bump for 5.0.0 release

assembly.xml
specify full path on exclude directive.  empirically this appears to prevent having the unsubstituted token in the built CSD jar
=> specify full path in exclude

pom.xml, src/aux/logback-container.xml.default, src/descriptor/service.sdl, src/scripts/cdap-control.sh
Updating for CDAP 6.0 `s/co.cask/io.cdap/g` package rename.
CSD 6.x will NOT be backwards compatible with CDAP 5.x.  Some compatibility has been added to at least be able to start/stop 5.x services, however the auth config, logback configurations, etc will still be invalid.  The upgrade procedure remains the same, where CSD/Parcel should be installed together
=> support for 6.0 cdap.io renaming
